language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: nE4zch2Q5G37nX0pDdypbNFsEJIjE+Ys4dL3Ta2p9uk6kBnSCWVmQU6JXvM541FY2ZV4w0hp1sbd0+TFMKXBXiSn7IXZR4ZzeydJk0UaeCEbtgwgHYrKNdlIdM5s12Qw0hAL9qNH/a5NN856I8V3BVBnRkfcDIvBDoXk0AdbXyd3+TRw6Uqf3NeHcDTedyH9Q4gmITQTwvTmsJ67DqUl6GBsnVoY2DLDRHSXDIb2dGnfC/8sCBan7IW9OZ0CtnuCF3MHUa0j8jELer0z3MPxOph6helcHdtDF9LYz9t6qoGulTf22EXmI+a/OAYUNVzJjGiemVi6MnhkmenLEvdZ0wyD4VKCXf1bAG70Q2+fJ5OoslYulNGW/o9/yP43M3zNLOocMHnUJOjOBeBCOy+URtpIv7pKusxgSARVsD53GeQh3i4GzJHzNbsKQViL8rf2TzrLVs2Wifa/nRQxz7zU1lqc3+raBCCq7zNtUzSx6/lIdbbDaRV3TZi3ibFV2JFrSI4PxkHv1NK7DA1TuuSa1y1JlMPn0oDS0SQdweWO6VwvBR66rbxq3j6pktGHZ4OjwROEFd6vZ4Udi4vDdfk3X7+ve+1Os5eH9zXiIi8C0ES9w8ssJgB0frMzRrq1TVIxB6fcJfwsWLHhgE+UFZW/psFwQqotR3H5K48INxGs6KU=
  app: viewing-party-ja
  run: rails db:migrate
  on:
    branch: main
